webshop/cart/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.cart.views',
    url(r'^$', 'cart_view', {'template_name':'cart/cart.html'}, name='show_cart'),
)

webshop/news/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.news.views',
# Главная страница
    url(r'^post/(?P<news_slug>[-\w]+)/$', 'news_view',
           {'template_name':'news/news.html'}, name='news'),
    url(r'^allnews/$', 'news_all_view',
           {'template_name':'news/news_all.html'}, name='news_all'),
    )

webshop/pages/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url
from django.contrib import admin

from webshop import settings

from webshop.pages.views import *

urlpatterns = patterns('webshop.pages.views',
    # url(r'^(?P<slug>[-_\w]+)/$', PageView.as_view(), name='page'),
    # url(r'^', PageList.as_view(), name='blog_posts'),
    url(r'^(?P<slug>[-_\w]+)/$', 'pageView',
        {'template_name':'pages/page.html'},
        name='page'),
)

webshop/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, include, url
from django.contrib import admin

from webshop import settings
from dajaxice.core import  dajaxice_autodiscover, dajaxice_config

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^webshop/', include('webshop.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # General application URLs
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('webshop.accounts.urls')),
    url(r'^', include('webshop.catalog.urls')),
    url(r'^cart/', include('webshop.cart.urls')),
    url(r'^page/', include('webshop.pages.urls')),
    url(r'^blog/', include('webshop.pages.blogurls')),
    url(r'^checkout/', include('webshop.checkout.urls')),
    url(r'^', include('webshop.news.urls')),
    url(r'^search/', include('webshop.search.urls')),
    url(r'^review/$', include('webshop.pages.reviewurls')),


    # enable language choice
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),

    # урл для robokassa
    # url(r'^robokassa/', include('robokassa.urls')),
    # url(r'^robokassa/result/', include('webshop.checkout.robokassa_urls')),
    url(r'^robokassa/', include('robokassa.urls')),

    )


# if settings.DEBUG:
#     urlpatterns += patterns('',
#     url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.STATIC_ROOT}),
#         # if work then show 404 Directory indexes are not allowed here.
#     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.MEDIA_ROOT}),
#         )

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
        )


handler404 = 'webshop.views.file_not_found_404'

webshop/ajaxapp/models.py
from django.db import models

# Create your models here.

webshop/checkout/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
import decimal

from django.contrib.auth.models import User
# from webshop.accounts.models import UserProfile
from django.db import models
from django.db.models import permalink
from django.utils.translation import ugettext_lazy as _

from webshop.catalog.models import *

class Delivery(models.Model):
    delivery_type = models.CharField(
        verbose_name=u'способ доставки',
        max_length=100,
        choices=(
            ('SPSurface', 'Small Packet Surface'),
            ('SPSAL', 'Small Packet SAL'),
            ('SPA' ,'Small Packet Air'),
            ('PS', 'Parcel Surface'),
            ('EMA', 'EMA'),
        ),
        default='',)
    weight = models.IntegerField(verbose_name=u'Вес', default=0)
    delivery_price = models.DecimalField(max_digits=9, decimal_places=0)
    cart_id_delivery = models.CharField(max_length=50, )

    gift = models.ForeignKey(GiftPrice, verbose_name=u'Доставить подарок', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.delivery_price

    def is_to_big(self):
        return self.weight > 20000

class BaseOrderInfo(models.Model):
    """Абстрактный класс для заказов"""
    class Meta:
        abstract = True

    # Контактная информация
    email = models.EmailField(max_length=50, verbose_name=(u'Ваш email'))
    phone = models.CharField(max_length=20, verbose_name=(u'Ваш телефон'))
    # Информация об адресе для отправки товара
    shipping_name = models.CharField(max_length=240, verbose_name=(u'ФИО получателя'))
    shipping_address_1 = models.TextField(verbose_name=(u'Адрес доставки'))
    shipping_city = models.CharField(max_length=200, verbose_name=(u'Город'))

    shipping_address_2 = models.TextField(verbose_name=(u'Дополнительный адрес(необязательно)'), blank=True)

    shipping_country = models.CharField(max_length=200, verbose_name=(u'Страна'))
    shipping_zip = models.CharField(max_length=10, verbose_name=(u'Почтовый индекс'))

class Order(BaseOrderInfo):
    """Класс для заказа"""

    # Константы статуса
    SUBMITTED = 1
    PAID = 2
    CURIER = 3

    # Словарь возможных статусов заказа
    ORDER_STATUSES = ((SUBMITTED, _(u'Принято')),
                      (PAID, _(u'Оплачено')),
                      (CURIER, _(u'Оплата квитанцией')),)

    # словарь способа оплаты
    PAYMENT_DICTIONARY = ((1, _(u'Оплатить квитанцию')),
                          (2, _(u'Оплатить Viza, MasterCard, ЯндексДеньги')),)

    # Информация о заказе
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=ORDER_STATUSES, default=SUBMITTED)
    payment_method = models.IntegerField(choices=PAYMENT_DICTIONARY, default=2)
    ip_address = models.IPAddressField()
    last_updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, null=True)
    transaction_id = models.CharField(max_length=20)

    # def cupon_is_zero(self):
    #     return Cupon.objects.get(identifier='zero')

    cupon = models.ForeignKey(Cupon, verbose_name=u'Использованый купон', blank=True, null=True)

    delivery = models.ForeignKey(Delivery, null=True)

    def __unicode__(self):
        return _(u'Order #') + str(self.id)

    @property
    def total(self):
        """Общая сумма заказа"""
        total = decimal.Decimal('0.00')
        order_items = OrderItem.objects.filter(order=self)
        for item in order_items:
            total += item.total
        total = total + self.delivery.delivery_price
        return total

    @permalink
    def get_absolute_url(self):
        """Абсолютная ссылка для просмотра заказа"""
        return ('order_details', (), { 'order_id': self.id })

    def get_shipping_name(self):
        return self.shipping_name

    # переопределяем метод сохранения что бы присвоить zero купон , если никакого другого не присваивали
    def save(self, force_insert=False, force_update=False, using=None):
        if not self.cupon:
            self.cupon = Cupon.objects.get(identifier='zero')
        return super(Order, self).save(force_insert, force_update, using)


class OrderItem(models.Model):
    """Конкретный товар в заказе"""
    product = models.ForeignKey(Product)
    feel = models.ForeignKey(FeelName, unique=False, default=None, null=True)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    order = models.ForeignKey(Order)
    # atribute = models.ForeignKey(ProductVolume, unique=False, default=None, null=False)
    # feel = models.ForeignKey(FeelName, null=True)
    atributes = models.ForeignKey(ProductVolume)


    @property
    def total(self):
        """Сумма для товара"""
        return self.quantity * self.price

    @property
    def name(self):
        """Название товара"""
        return self.product.name

    def get_feel(self):
        try:
            f = self.feel.name
            return  f
        except Exception:
            return None


    def __unicode__(self):
        return self.product.name
               # + ' (' + self.product.sku + ')'

    def get_absolute_url(self):
        """Абсолютная ссылка на товар в корзине"""
        return self.product.get_absolute_url()

class OrderOneClick(models.Model):
    product_name = models.CharField(max_length=128, verbose_name=u'Имя продукта')
    phone = models.CharField(max_length=20, verbose_name=u'Телефон')

    class Meta:
        verbose_name = ('Заказы')
        verbose_name_plural = ('Заказы в 1 клик')
        ordering = ['product_name']

    def __unicode__(self):
        return self.product_name

webshop/pages/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from ckeditor.widgets import CKEditorWidget

from webshop.pages.models import *

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user',)


class PageForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Page
        exclude = ()
        # exclude = ('slug',)

webshop/search/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms

from webshop.search.models import SearchTerm


class SearchForm(forms.ModelForm):
    """Форма поиска"""
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        default_text = u'Search...'
        self.fields['query'].widget.attrs['value'] = default_text
        self.fields['query'].widget.attrs['onfocus'] = "if (this.value == '" + default_text + "')this.value = ''"
    include = ('query',)

    class Meta:
        model = SearchTerm
        exclude = ()


webshop/accounts/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

import decimal
from webshop.settings import ADMIN_EMAIL
from django.core.mail import send_mail, EmailMultiAlternatives
from webshop.checkout.models import Order, OrderItem
from webshop.accounts.forms import UserProfileForm, MyRegistrationForm
from webshop.accounts import profile


@csrf_protect
def register_view(request, template_name="registration/register.html"):
    """Регистрация нового пользователя"""
    page_title = _(u'User Registration')
    request.breadcrumbs(page_title, request.path_info)
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = MyRegistrationForm(postdata)
        if form.is_valid():
            form.save()
            un = postdata.get('username', '')
            # name="password1" т.к. два поля с подтверждением
            pw = postdata.get('password1', '')
            new_user = authenticate(username=un, password=pw)
            if new_user and new_user.is_active:

                # отправляем e-mail о регистрации нового пользователя
                subject = u'polythai.ru регистрация %s' % new_user.username
                message = u' Зарегистрирован новый пользователь %s' % (new_user.username)
                send_mail(subject, message, 'teamer777@gmail.com', [ADMIN_EMAIL], fail_silently=False)

                login(request, new_user)
                # Редирект на url с именем my_account
                url = urlresolvers.reverse('my_account')
                return HttpResponseRedirect(url)
    else:
        form = MyRegistrationForm()

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def my_account_view(request, template_name="registration/my_account.html"):
    """Страница аккаунта пользователя"""
    page_title = _(u'My Account')
    request.breadcrumbs(page_title, request.path_info)
    if request.user.is_superuser:
        orders = Order.objects.all()
    else:
        orders = Order.objects.filter(user=request.user)
    name = request.user.username
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_details_view(request, order_id, template_name="registration/order_details.html"):
    """Информация о сделанном заказе"""
    if request.user.is_superuser:
        order = get_object_or_404(Order, id=order_id)
    else:
        order = get_object_or_404(Order, id=order_id, user=request.user)
    page_title = _(u'Order details for order #') + order_id
    request.breadcrumbs(page_title, request.path_info)
    order_items = OrderItem.objects.filter(order=order)
    total_sum_parse = "%s" % order.total
    total_sum_parse = total_sum_parse.split(".")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def receipt_print_view(request, price, template_name="checkout/receipt_print.html"):
    price = price.split("-")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_info_view(request, template_name="registration/order_info.html"):
    """Представление данных профиля"""
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = UserProfileForm(postdata)
        if form.is_valid():
            profile.set(request)
            url = urlresolvers.reverse('my_account')
            return HttpResponseRedirect(url)
    else:
        user_profile = profile.retrieve(request)
        form = UserProfileForm(instance=user_profile)
    page_title = _(u'Edit Order Information')
    request.breadcrumbs(page_title, request.path_info)
    return render_to_response(template_name, locals(),
                                  context_instance=RequestContext(request))

webshop/ajaxapp/views.py
# Create your views here.

webshop/cart/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

from webshop.cart import cart
from webshop.checkout import checkout
from webshop.checkout.forms import ContactForm, DeliveryForm


@csrf_protect
def cart_view(request, template_name="cart/cart.html"):
    """Представление для отображения корзины"""
    page_title = _(u'Shopping cart')
    if request.method == 'POST':
        postdata = request.POST.copy()

        if postdata.has_key('remove'):
            cart.remove_from_cart(request)

        if postdata.has_key('update'):
            cart.update_cart(request)

        """отправляем request на пересчет корзины по купону"""
        if postdata.has_key('update_cupon'):
            cart.update_cupon_cart(request)


        if postdata.has_key('checkout'):
            checkout_url = checkout.get_checkout_url(request)
            return HttpResponseRedirect(checkout_url)

    deliveryForm = DeliveryForm()

    request.breadcrumbs(u'Корзина', request.path_info)

    # Получаем список всех товаров в корзине из cookies
    #cart_item_count = cart.cart_item_count(request)
    cart_items = cart.get_cart_items(request)
    cart_subtotal = cart.cart_subtotal(request)
    cart_gift = cart.cart_gift_add(request)

    # доставка
    try: 
        delivery = cart.get_delivery(request)
        delivery.save()
        cart_total = cart.cart_total(request)
    except Exception:
        return redirect("/")

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

webshop/news/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _

from models import News

from django.shortcuts import get_object_or_404


def news_view(request, news_slug, template_name="news.html"):
    """Представление для конкретной новости"""
    news = get_object_or_404(News, slug=news_slug)
    return render_to_response(template_name,
            {'news': news,}, context_instance=RequestContext(request))

def news_all_view(request, template_name="news_all.html"):
    """Представление для конкретной новости"""
    news = News.objects.all()
    return render_to_response(template_name,
            {'news': news}, context_instance=RequestContext(request))


webshop/templates/checkout/checkout.html
{% extends "catalog.html" %}
{% load i18n %}
{% block slider %}
{% endblock %}
{% block tri_bloka %}
{% endblock %}
{% load checkout_tags %}
{% load dajaxice_templatetags %}

{% block content %}
    <div id="checkout" xmlns="http://www.w3.org/1999/html">
            <div class="row">
                <div class="alert alert-info col-xs-5">
                    <strong>{% trans "Warning" %}!</strong><br /> * {% trans "Required fields" %}
                </div>

                {% if not request.user.is_authenticated %}
{#                    <div class="row-fluid">#}
                          <a href="{% url 'login' %}?next={{ request.path }}">
                            {% trans "Have an account" %}?<br />{% trans "Sign in now" %}!
                          </a>
{#                    </div>#}
                {% endif %}

{#                <div class="row-fluid">#}
{#                    <div class="row">#}
                      <div class="col-xs-12">
{#                          <div class="col-xs-3 checkout">#}
                             <h1>Контакты для доставки</h1>
{#                          </div>#}
                      </div>
{#                    </div>#}

                    {% if error_message %}
{#                        <div class="row-fluid">#}
                            <div class="alert alert-error span5">
                                {{ error_message }}
                            </div>
{#                        </div>#}
                    {% endif %}

{#                    <form action="." id="my_form" method="post">#}
{#                        {% csrf_token %}#}
{#                        {{ form.as_p }}#}
{#                        <input id="order_submit" class="btn btn-primary" value="Отправить" type="submit"/>#}
{#                        <div id="checkout_form">#}
{#                                <div class="row">#}
{#                                    <div class="col-xs-6 border_chec">#}
{#                                        <div class="border_chec2 col-xs-6 ">#}
{#                                            <label for="id_email">Ваш email:</label>#}
{#                                            {% if error.email %}{{ error.email }}{% endif %}#}
{#                                            {{form.email}}#}
{#                                            <label for="id_email">Ваш телефон:</label>#}
{#                                            {% if error.phone %}{{ error.phone }}{% endif %}#}
{#                                            {{form.phone}}#}
{#                                            <label for="id_shipping_name">Ваше имя:</label>#}
{#                                            {% if error.shipping_name %}{{ error.shipping_name }}{% endif %}#}
{#                                            {{form.shipping_name}}#}
{#                                        </div>#}
{#                                        <div class="col-xs-6">#}
{#                                            <label for="id_shipping_address_1">Ваш адрес:</label>#}
{#                                            {% if error.shipping_address_1 %}{{ error.shipping_address_1 }}{% endif %}#}
{#                                            {{form.shipping_address_1}}#}
{#                                            <label for="id_shipping_address_2">Ваш адрес 2:</label>#}
{#                                            {% if error.shipping_address_2 %}{{ error.shipping_address_2 }}{% endif %}#}
{#                                            {{form.shipping_address_2}}#}
{#                                            <label for="id_shipping_country">Страна доставки:</label>#}
{#                                            {% if error.shipping_country %}{{ error.shipping_country }}{% endif %}#}
{#                                            {{form.shipping_country}}#}
{#                                            <label for="id_shipping_zip">Почтовый индекс:</label>#}
{#                                            {% if error.shipping_zip %}{{ error.shipping_zip }}{% endif %}#}
{#                                            {{form.shipping_zip }}#}
{#                                            <label for="id_shipping_city">Город:</label>#}
{#                                            {% if error.shipping_city %}{{ error.shipping_city }}{% endif %}#}
{#                                            {{form.shipping_city}}#}
{#                                            <input id="order_submit" class="btn btn-primary" value="Отправить" type="submit"/>#}
{#                                            <input id="order_submit" class="btn btn-primary" value="Отправить" type="button" onclick="order_form();">#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                        </div>#}
{#                    </form>#}

{#                </div>#}
            </div>
    </div>

    <form action="." id="my_form" method="post">
        {% csrf_token %}
        <table id="shipping_form">
        {{ form.as_table }}
        </table>
        <div style="float: right;">

{#            <input id="order_submit" class="btn btn-primary" value="Заказать" type="submit"/>#}

            <a class="btn btn-primary" name="" data-toggle="modal" data-target="#paymentModal">Оплатить</a>
            <div class="modal modal-primary fade" id="paymentModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog" style="margin-top: 90px;">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                            <h4 class="modal-title">Выберете способ оплаты</h4>
                        </div>
                        <div class="modal-body" style="overflow: hidden;">
                            <div class="col-xs-6">
                                <input type="radio" name="payment_method" value="2" id="online" disabled/>
                                <label for="online" class="blue">
                                    <i style="font-size: 30px;" class="fa fa-credit-card"></i>
                                    <p>Оплата онлайн</p>
                                    <p>Выбирая этот способ вы можете оплатить заказ онлайн, через банковскую карту Visa MasterCard, яндекс деньги, Qiwi кошелек и др. </p>
                                </label>
                            </div>
                            <div class="col-xs-6">
                                <input type="radio" name="payment_method" value="1" id="offline"/>
                                <label for="offline" class="blue">
                                    <i style="font-size: 30px;" class="fa fa-cc-visa"></i>
                                    <p>Перевод на карту</p>
                                    <p>Выбирая этот способ оплаты Вы можете оплатить только с помощью перевода на карту сбербанк. Дальнешие инструкции придут на почтовый адрес, указанный вами.</p>
                                </label>

                            </div>
{#                            <select style="" name="payment_method" id="">#}
{#                                <option value="2">Оплатить онлайн</option>#}
{#                                <option value="1">Оплата на карту</option>#}
{#                            </select><br/>#}
                        </div>
                        <div class="modal-footer">
                            <input id="order_submit" class="btn btn-primary disabled" value="Оплатить" type="submit"/>
                        </div>
                    </div><!-- /.modal-content -->
                </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->
        </div>
    </form>
{% endblock %}

{% block bottom_script %}
   <script>
        $("input[name=payment_method]").live("change", function(){
            $("#order_submit").removeClass('disabled');
        });
    </script>
{% endblock %}

webshop/templates/checkout/email.html
<h3>Здравствуйте!</h3>

<p>Спасибо за ваш заказ! Оплата вашего заказа поступила на счет нашего магазина!</p>
<p>Товары по Вашему заказу и презент от нашего интернет магазина будут отправлены по указанному Вами адресу в течение 3-4 рабочих дней.
    В день отправки товаров на Вашу почту будет выслан трекинг-код для отслеживания местоположения вашей посылки и фото вашего укомплектованного заказа.</p>
<div>
    <p>№ Вашей операции: {{ transaction }}</p>
    <p>id Вашего заказа: {{ id }}</p>
    <p>Выбранные товары: </p>
    <p style="font-weight: bold;">{{ items }}</p>
</div>

<div>
    <br/>
    <p>Спасибо,что выбрали нас!</p>
    <h3>С уважением, www.PolyThai.ru</h3>
    <p><img width="400px" src="http://polythai.ru/static/images/logo.png" alt="логотип"/></p>
    <p><a href="http://polythai.ru/">http://polythai.ru/</a></p>
    <p><a href="mailto:PolyThai@mail.ru">PolyThai@mail.ru</a></p>
</div>

webshop/templates/checkout/email_1.html
<h3>Здравствуйте!</h3>

<p>Спасибо за ваш заказ! Вы выбрали оплату переводом на сбербанк карту.</p>
<p>Товары по Вашему заказу и презент от нашего интернет магазина будут отправлены по указанному Вами адресу в течение 3-4 рабочих дней с момента оплаты.
    В день отправки товаров на Вашу почту будет выслан трекинг-код для отслеживания местоположения вашей посылки и фото вашего укомплектованного заказа.</p>
<p><strong>Внимание!</strong> Обязательно прокомментируйте id своего заказа при переводе средств либо напишите сообщение по указанным на сайте контактам!</p>
<div>
    <p>№ Вашей операции: {{ transaction }}</p>
    <p>id Вашего заказа: {{ id }}</p>
    <p>Выбранные товары: </p>
    <p style="font-weight: bold;">{{ items }}</p>
</div>

<table width="720" bordercolor="#000000" style="border:#000000 1px solid;" cellpadding="0" cellspacing="0">
    <tbody>
        <tr>
            <td width="220" valign="top" height="100" align="center" style="border-bottom:#000000 1px solid; border-right:#000000 1px solid;">&nbsp;<strong>Перевод на сбербанк карту</strong></td>
            <td valign="top" style="border-bottom:#000000 1px solid; border-right:#000000 1px solid;">
                <li><strong>Получатель: </strong> <font style="font-size:90%"> Силина Елена Николаевна</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Наименование банка: </strong><font style="font-size:90%"> ОАО Сбербанк России</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Адрес отделения: </strong><font style="font-size:90%"> Доп офис номер 9038/0400 индекс 103051 г. Москва , бульвар Цветной 28, стр. 1</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Номер карты: </strong> <font style="font-size:90%">4279 3800 2655 4735</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Номер счета: </strong> <font style="font-size:90%">40817810638091042661</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>ИНН банка: </strong> <font style="font-size:90%"> 7707083893</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>БИК банка: </strong> <font style="font-size:90%"> 044525225</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Корр. счет банка: </strong> <font style="font-size:90%"> 30101810400000000225</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>КПП: </strong> <font style="font-size:90%"> 775001001</font>&nbsp;&nbsp;&nbsp;<br></li>
                <li><strong>Сумма:</strong> {% if price_order %}{{ price_order|first }}{% endif %} {% if price %}{{ price|first }}{% endif %} руб. {% if price_order %}{{ price_order|last }}{% endif %}{% if price %}{{ price|last }}{% endif %} коп.&nbsp;&nbsp;</li>
            </td>
        </tr>
    </tbody>
</table>
<div>
    <br/>
    <p>Спасибо,что выбрали нас!</p>
    <h3>С уважением, www.PolyThai.ru</h3>
    <p><img width="400px" src="http://polythai.ru/static/images/logo.png" alt="логотип"/></p>
    <p><a href="http://polythai.ru/">http://polythai.ru/</a></p>
    <p><a href="mailto:PolyThai@mail.ru">PolyThai@mail.ru</a></p>
</div>

webshop/templates/checkout/reg_email.html
<h3> {{ name }}, здравствуйте!</h3>

<p>Добро пожаловать и благодарим Вас за регистрацию в нашем интернет магазине тайских товаров — PolyThai.ru!</p>
<p>Ваш аккаунт создан и Вы можете войти в ваш личный кабинет, используя следующие данные: </p>
<p><strong>Имя ползователя</strong>: {{ username }}</p>
<p><strong>Пароль</strong>: {{ password }}</p>

<p>Ссылка для входа в ваш личный кабинет: http://polythai.ru/accounts/login/</p>

<div>
    <p>Спасибо,что выбрали нас!</p>
    <h3>С уважением, www.PolyThai.ru</h3>
    <p><img width="400px" src="http://dev.polythai.ru/static/images/logo.png" alt="логотип"/></p>
    <p><a href="http://polythai.ru/">http://polythai.ru/</a></p>
    <p><a href="mailto:PolyThai@mail.ru">PolyThai@mail.ru</a></p>
</div>