webshop/cart/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.cart.views',
    url(r'^$', 'cart_view', {'template_name':'cart/cart.html'}, name='show_cart'),
)

webshop/news/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.news.views',
# Главная страница
    url(r'^post/(?P<news_slug>[-\w]+)/$', 'news_view',
           {'template_name':'news/news.html'}, name='news'),
    url(r'^allnews/$', 'news_all_view',
           {'template_name':'news/news_all.html'}, name='news_all'),
    )

webshop/pages/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url
from django.contrib import admin

from webshop import settings

from webshop.pages.views import *

urlpatterns = patterns('webshop.pages.views',
    # url(r'^(?P<slug>[-_\w]+)/$', PageView.as_view(), name='page'),
    # url(r'^', PageList.as_view(), name='blog_posts'),
    url(r'^(?P<slug>[-_\w]+)/$', 'pageView',
        {'template_name':'pages/page.html'},
        name='page'),
)

webshop/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, include, url
from django.contrib import admin

from webshop import settings
from dajaxice.core import  dajaxice_autodiscover, dajaxice_config

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^webshop/', include('webshop.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # General application URLs
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('webshop.accounts.urls')),
    url(r'^', include('webshop.catalog.urls')),
    url(r'^cart/', include('webshop.cart.urls')),
    url(r'^page/', include('webshop.pages.urls')),
    url(r'^blog/', include('webshop.pages.blogurls')),
    url(r'^checkout/', include('webshop.checkout.urls')),
    url(r'^', include('webshop.news.urls')),
    url(r'^search/', include('webshop.search.urls')),
    url(r'^review/$', include('webshop.pages.reviewurls')),


    # enable language choice
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),

    # урл для robokassa
    # url(r'^robokassa/', include('robokassa.urls')),
    # url(r'^robokassa/result/', include('webshop.checkout.robokassa_urls')),
    url(r'^robokassa/', include('robokassa.urls')),

    )


# if settings.DEBUG:
#     urlpatterns += patterns('',
#     url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.STATIC_ROOT}),
#         # if work then show 404 Directory indexes are not allowed here.
#     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.MEDIA_ROOT}),
#         )

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
        )


handler404 = 'webshop.views.file_not_found_404'

webshop/ajaxapp/models.py
from django.db import models

# Create your models here.

webshop/search/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.db import models
from django.contrib.auth.models import User


class SearchTerm(models.Model):
    """Класс для хранения поисковых запросов"""
    query = models.CharField(max_length=50)
    search_date = models.DateTimeField(auto_now_add=True)
    ip_address = models.IPAddressField()
    user = models.ForeignKey(User, null=True)

    class Meta:
    	db_table = 'search_terms'
    	ordering = ['query']

    def __unicode__(self):
        return self.query

webshop/accounts/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _

from captcha.fields import CaptchaField

from models import UserProfile


class UserProfileForm(forms.ModelForm):
    """Форма для профиля пользователя"""
    class Meta:
        model = UserProfile
        exclude = ('user',)


class MyRegistrationForm(forms.ModelForm):

    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username"), max_length=100,
        regex=r'^[\w.@+-]+$',
        help_text = u"Пожалуйста введите имя пользователя латинскими буквами и цифрами не более 40 символов, допускаются также следующие символы: @ . + - _ ",
        error_messages = {
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
                                help_text = u"Пароль может состоять из Заглавных и прописных латинских букв и цифр",
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text = _("Enter the same password as above, for verification."))
    captcha = CaptchaField(label=u'Введите символы с картинки',
                           help_text = u"Введите то что вы видите на картинке в рядом стоящее поле",)

    class Meta:
        model = User
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



webshop/catalog/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.utils.translation import ugettext_lazy as _

from models import Product, Category, FeelName
from webshop.checkout.models import OrderOneClick


class ProductAdminForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ()

    def clean_price(self):
        """Проверка поля цена"""
        if self.cleaned_data['price'] <= 0:
            raise forms.ValidationError(_(u'Price must be greater than zero.'))
        return self.cleaned_data['price']

    def __init__(self, *args, **kwds):
        super(ProductAdminForm, self).__init__(*args, **kwds)
        self.fields['categories'].queryset = Category.objects.order_by('created_at')

def feelList_request():
    feelList = FeelName.objects.all()
    dictionary = {}
    for feel in feelList:
        dictionary[feel.id] = '%s' % feel.name

    return dictionary


def get_form_add_to_cart(request, postdata):
    if request.method == 'POST':
        product = Product.objects.get(slug=postdata.get('product_slug', ''))
        feels_product = product.feel
        test = 123
    form = ProductAddToCartForm(request, postdata)
    return form


class ProductAddToCartForm(forms.Form):
    """Форма добавления товара в корзину"""

    # FEEL_CHOICES = feelList_request()

    # feel = forms.ModelChoiceField(queryset=FeelName.objects.all(),
    #                               widget=forms.Select(attrs={'id':'name'}), required=True)
    # feel = forms.ModelChoiceField(widget=forms.Select(attrs={'id':'name'}), required=True)
    quantity = forms.IntegerField(widget=forms.TextInput(attrs={'size': '2',
                                                                'value': '1', 'class': 'quantity', 'maxlength': '5'}),
        error_messages={'invalid': _(u'Please enter a valid quantity.')},
        min_value=1)
    product_slug = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, request=None, *args, **kwargs):
        """
        Переопределение метода __init__ по умолчанию для получения словаря request
        нужен для проверки работы cookies
        """

        self.request = request
        super(ProductAddToCartForm, self).__init__(*args, **kwargs)
        # self.fields['feel'].queryset = Y.objects.filter(id_X=x)
        # self.fields['feel'].queryset = Product.objects.get(slug=self.product_slug)
        # obj = self.fields['product_slug']
        # test = 123



    def clean(self):
        """Проверка что cookies в браузере включены"""
        if self.request:
            if not self.request.session.test_cookie_worked():
                raise forms.ValidationError(_(u'Cookies must be enabled.'))
        return self.cleaned_data


class ProductOneClickForm(forms.ModelForm):
    # phone = forms.CharField(label=u'Ваш телефон (обязательно)', max_length=255)
    # product_slug = forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = OrderOneClick
        exclude = ()

        # exclude = ('product_name')
        # widgets = {
        #     'phone': forms.TextInput(attrs={'placeholder': "Ваш телефон"}),
        #     'description': forms.Textarea(
        #         attrs={'placeholder': 'Enter description here'}),
        # }

webshop/accounts/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

import decimal
from webshop.settings import ADMIN_EMAIL
from django.core.mail import send_mail, EmailMultiAlternatives
from webshop.checkout.models import Order, OrderItem
from webshop.accounts.forms import UserProfileForm, MyRegistrationForm
from webshop.accounts import profile


@csrf_protect
def register_view(request, template_name="registration/register.html"):
    """Регистрация нового пользователя"""
    page_title = _(u'User Registration')
    request.breadcrumbs(page_title, request.path_info)
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = MyRegistrationForm(postdata)
        if form.is_valid():
            form.save()
            un = postdata.get('username', '')
            # name="password1" т.к. два поля с подтверждением
            pw = postdata.get('password1', '')
            new_user = authenticate(username=un, password=pw)
            if new_user and new_user.is_active:

                # отправляем e-mail о регистрации нового пользователя
                subject = u'polythai.ru регистрация %s' % new_user.username
                message = u' Зарегистрирован новый пользователь %s' % (new_user.username)
                send_mail(subject, message, 'teamer777@gmail.com', [ADMIN_EMAIL], fail_silently=False)

                login(request, new_user)
                # Редирект на url с именем my_account
                url = urlresolvers.reverse('my_account')
                return HttpResponseRedirect(url)
    else:
        form = MyRegistrationForm()

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def my_account_view(request, template_name="registration/my_account.html"):
    """Страница аккаунта пользователя"""
    page_title = _(u'My Account')
    request.breadcrumbs(page_title, request.path_info)
    if request.user.is_superuser:
        orders = Order.objects.all()
    else:
        orders = Order.objects.filter(user=request.user)
    name = request.user.username
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_details_view(request, order_id, template_name="registration/order_details.html"):
    """Информация о сделанном заказе"""
    if request.user.is_superuser:
        order = get_object_or_404(Order, id=order_id)
    else:
        order = get_object_or_404(Order, id=order_id, user=request.user)
    page_title = _(u'Order details for order #') + order_id
    request.breadcrumbs(page_title, request.path_info)
    order_items = OrderItem.objects.filter(order=order)
    total_sum_parse = "%s" % order.total
    total_sum_parse = total_sum_parse.split(".")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def receipt_print_view(request, price, template_name="checkout/receipt_print.html"):
    price = price.split("-")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_info_view(request, template_name="registration/order_info.html"):
    """Представление данных профиля"""
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = UserProfileForm(postdata)
        if form.is_valid():
            profile.set(request)
            url = urlresolvers.reverse('my_account')
            return HttpResponseRedirect(url)
    else:
        user_profile = profile.retrieve(request)
        form = UserProfileForm(instance=user_profile)
    page_title = _(u'Edit Order Information')
    request.breadcrumbs(page_title, request.path_info)
    return render_to_response(template_name, locals(),
                                  context_instance=RequestContext(request))

webshop/ajaxapp/views.py
# Create your views here.

webshop/cart/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

from webshop.cart import cart
from webshop.checkout import checkout
from webshop.checkout.forms import ContactForm, DeliveryForm


@csrf_protect
def cart_view(request, template_name="cart/cart.html"):
    """Представление для отображения корзины"""
    page_title = _(u'Shopping cart')
    if request.method == 'POST':
        postdata = request.POST.copy()

        if postdata.has_key('remove'):
            cart.remove_from_cart(request)

        if postdata.has_key('update'):
            cart.update_cart(request)

        """отправляем request на пересчет корзины по купону"""
        if postdata.has_key('update_cupon'):
            cart.update_cupon_cart(request)


        if postdata.has_key('checkout'):
            checkout_url = checkout.get_checkout_url(request)
            return HttpResponseRedirect(checkout_url)

    deliveryForm = DeliveryForm()

    request.breadcrumbs(u'Корзина', request.path_info)

    # Получаем список всех товаров в корзине из cookies
    #cart_item_count = cart.cart_item_count(request)
    cart_items = cart.get_cart_items(request)
    cart_subtotal = cart.cart_subtotal(request)
    cart_gift = cart.cart_gift_add(request)

    # доставка
    try: 
        delivery = cart.get_delivery(request)
        delivery.save()
        cart_total = cart.cart_total(request)
    except Exception:
        return redirect("/")

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

webshop/news/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _

from models import News

from django.shortcuts import get_object_or_404


def news_view(request, news_slug, template_name="news.html"):
    """Представление для конкретной новости"""
    news = get_object_or_404(News, slug=news_slug)
    return render_to_response(template_name,
            {'news': news,}, context_instance=RequestContext(request))

def news_all_view(request, template_name="news_all.html"):
    """Представление для конкретной новости"""
    news = News.objects.all()
    return render_to_response(template_name,
            {'news': news}, context_instance=RequestContext(request))


webshop/templates/tags/brand_filter.html
{% load i18n %}
{% load catalog_tags %}
{% load thumbnail %}


{% if brand_items %}
    <div class="">
        <form action="/search/brend/" method="get" id="">
            <select name="query" id="" onchange="this.form.submit();">
                <option value="">Не выбрано</option>
                {% for brand in brand_items %}
                    <option value="{{ brand.name }}">{{ brand.name }}</option>
                {% endfor %}
            </select>
        </form>
    </div>
{% else %}
    <p>Нет лидеров</p>
{% endif %}

webshop/templates/tags/cart_box.html
{% load i18n %}
{% load catalog_tags %}
{% load thumbnail %}

<ul class="nav">
  <li class="dropdown">
    <a href="{% url 'show_cart' %}" class="dropdown-toggle" data-toggle="dropdown">
        <n style="font-size: 20px;">Корзина</n> <i class="icon-addtocart"><span >{{ cart_i.count }}</span></i>
    </a>
    <ul class="dropdown-menu">

        <div class="pre-scrollable">

        <div class="cart_items_menu">
            {% if cart_i %}
                {% for item in cart_i %}
                    <div class="cart_items_prod">
{#                        {% thumbnail item.product.get_image.url "100x100" crop="center" as im %}#}
                            <img src="/media/{{  item.product.get_image.url }}" width="88" height="88">
{#                        {% endthumbnail %}#}

                        <div class="text_item">
                            <p class="name_item">{{ item.product.name }}</p>
                            <p>Цена: <i class="fa fa-rub"></i>{{ item.atributes.price }}</p>
                            <p>Колличество: {{ item.quantity }}</p>
                        </div>
                    </div>
                {% endfor %}
                <a href="{% url 'show_cart' %}" class="btn btn-success"><i class="icon-shopping-cart icon-white" style="margin-right: 5px;"></i> Показать корзину</a>
            {% else %}
                <p>Нет товаров в корзине</p>
            {% endif %}
        </div>

        </div>

    </ul>
  </li>
</ul>

webshop/templates/tags/category_list.html
{% load i18n %}
{% load mptt_tags %}

<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        {% recursetree nodes %}
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
                    <a class="accordion_button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ node.id }}">{% if not node.is_leaf_node %} <i class="fa fa-caret-down"></i>{% endif %}</a>
                </h4>
            </div>
            {% if not node.is_leaf_node %}
                <div id="collapse{{ node.id }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        {{ children }}<br/>
{#                        {% for foo in children %}#}
{#                            <i class="fa fa-angle-right"></i>#}
{#                        {% endfor %}#}

                    </div>
                </div>
            {% endif %}
        {% endrecursetree %}
    </div>
</div>

webshop/templates/tags/footer.html
{% load i18n %}
<a href="{% url 'catalog_home' %}">{% trans "Home" %}</a>
{% with flatpage_list as pages %}
	{% for page in pages %}
		<a href="{{ page.url }}">{{ page.title }}</a>
	{% endfor %}
{% endwith %}
<a href="{% url 'show_cart' %}">{% trans "Shopping cart" %}</a>

webshop/templates/tags/form_choice_field.html
<div class="control-group">
  <label class="control-label" for="{{ form_field.auto_id }}">
    {% if form_field.field.required %}* {% endif %}{{ form_field.label }}
  </label>
  <div class="controls">
    {{ form_field }}
  </div>
</div>

webshop/templates/tags/form_row.html
{% if form_field.errors %}
<div class="control-group error">
{% else %}
<div class="control-group">
{% endif %}
  <label class="control-label" for="{{ form_field.auto_id }}">
  {% if form_field.field.required %}* {% endif %}{{ form_field.label }}
  </label>
  <div class="controls">
    <input type="text" class="input-xlarge" id="{{ form_field.auto_id }}" />
    {% for error in form_field.errors %}
      <span class="help-inline">{{ error }}</span>
    {% endfor %}
  </div>
</div>

webshop/templates/tags/lider_box.html
{% load i18n %}
{% load catalog_tags %}
{% load thumbnail %}


{% if lider_items %}
    {% for item in lider_items %}
        <div class="leader_item">
            <a href="{{ item.get_absolute_url }}" class="name_item">{{ item.name }}</a>
{#            {% thumbnail item.get_image.url "100x100" crop="center" as im %}#}
                <img src="/media/{{ item.get_image.url }}" width="100" height="100">
{#            {% endthumbnail %}#}
            <div class="text_item">
{#                <p><strong>Бренд:</strong> {{ item.brand_name }}</p>#}
{#                <p>Описание: {{ item.description|truncatewords:10|safe }}</p>#}
{#                <p><strong>Объем:</strong> {{ item.get_atributes.volume }} мл.</p>#}
{#                <p><strong>Вес:</strong> {{ item.get_atributes.weight }} гр.</p>#}
{#                {% if item.is_not_available %}#}
{#                    <p style="color: red;">Нет в наличии</p>#}
{#                {% endif %}#}
                {% if item.sale_price.new_price != 0.00 %}
                    <div class="price_was">
                        {% trans "Was" %}: <span>{{ item.sale_price.price }} {% trans "руб." %}</span>
                    </div>
                    <div class="price_now">
                        {% trans "Now" %}:<span> {{ item.sale_price.new_price }} {% trans "руб." %}</span>
                    </div>
{#                    <p>*за объем: {{ item.sale_price.volume }} мл.</p>#}
                {% else %}
                    <p>{{ item.sale_price.price }} {% trans "руб." %}</p>
                {% endif %}
                <p></p>
            </div>
        </div>
    {% endfor %}
{% else %}
    <p>Нет лидеров</p>
{% endif %}

webshop/templates/tags/navigation.html
{% load i18n %}
<ul>
	<li><a href="{% url 'catalog_home' %}">{% trans "Home" %}</a></li>
	<li><a href="/about/">{% trans "About" %}</a></li>
	<li><a href="/privacy-policy/">{% trans "Privacy" %}</a></li>
	<li><a href="/about/contacts/">{% trans "Contact" %}</a></li>
</ul>
<div class="cb"></div>

webshop/templates/tags/pagination_links.html
{% load i18n %}

{% if p.has_other_pages %}
    {% if p.has_previous %}
        <a href="{{ request.path }}?{{ params }}&amp;page={{ p.previous_page_number }}">
            &laquo; {% trans "Previous" %}
        </a>
    {% else %}
        &laquo; Previous
    {% endif %}
    | {% trans "Page" %} {{ p.number }} {% trans "of" %} {{ paginator.num_pages }} |
    {% if p.has_next %}
        <a href="{{ request.path }}?{{ params }}&amp;page={{ p.next_page_number }}">
            {% trans "Next" %} &raquo;
        </a>
    {% else %}
      {% trans "Next" %} &raquo;
    {% endif %}
{% endif %}

webshop/templates/tags/search_box.html
{% load i18n %}

<div class="row">
    <div class="col-xs-12">
        <div class="row">
            <form class="navbar-search" id="id_query" action="{% url 'search_results' %}" method="get">
                <div class="col-xs-8">
                    <input name="query" width="200" id="{{ form.auto_id }}" type="text"
                         value="Поиск" class="search-query span2" placeholder="Поиск"
                         onfocus="if(this.value == 'Поиск') { this.value = ''; }" />
                </div>
                <div class="col-xs-4">
{#                    <i class="fa fa-search"></i>#}
                    <input class="btn btn-success" type="submit" value="Поиск"/>
                </div>
            </form>
        </div>
    </div>
</div>

webshop/templates/tags/slider.html
{% load i18n %}
{% load catalog_tags %}
{#            flex-slider#}
<div class="my_slider">
    <section class="flexslider-wrapper ">
        <div class="flexslider" data-slidernav="auto" data-transition="slide" id="flexslider-0">
            <div class="slides" style="width:800%; -webkit-transition: 0s; transition: 0s; -webkit-transform: translate3d(-1170px, 0, 0);">
                {% for slide in slides %}
                    <div class="slide row-fluid" style="background: url('/media/{{ slide.image }}');">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6 caption">
                                    <h2 class="enlarge">{{ slide.product.name }}</h2>
                                    <h4>{{ slide.product.brand }}</h4>
                                    <p>{{ slide.product.description }}</p>
                                    <a href="{{ slide.product.get_absolute_url }}" class="btn more-link large i-right">Подробнее<i class="default"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

                <!--Slide #1 with caption-->
{#                        <div class="slide row-fluid first flex-active-slide animate-in" style="width: 100%; float: left; display: block; background: url('/static/images/bg-slide0.jpg');">#}
{#                            <div class="container">#}
{#                                <div class="row">#}
{#                                    <div class="col-md-6 caption">#}
{#                                        <h2 class="enlarge">Welcome to <span class="em">Flexor</span></h2>#}
{#                                        <h4>Super flexible responsive theme with a modest design touch.</h4>#}
{#                                        <p>Perfect for your App, Web service, company or portfolio! Magna tincidunt sociis ac integer amet non. Rhoncus augue? Tempor porttitor sed, aliquet phasellus a, nisi nunc aliquet nec rhoncus enim porttitor ultrices lacus tristique?</p>#}
{#                                        <a href="https://wrapbootstrap.com/user/themelize_me" class="btn more-link large i-right">Buy Now <i class="default"></i></a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <!--Slide #1 with caption-->#}
{#                        <div class="slide row-fluid first flex-active-slide animate-in" style="width: 100%; float: left; display: block; background: url('/static/images/bg-slide1.jpg');">#}
{#                            <div class="container">#}
{#                                <div class="row">#}
{#                                    <div class="col-md-6 caption">#}
{#                                        <h2 class="enlarge">Welcome to <span class="em">Flexor</span></h2>#}
{#                                        <h4>Super flexible responsive theme with a modest design touch.</h4>#}
{#                                        <p>Perfect for your App, Web service, company or portfolio! Magna tincidunt sociis ac integer amet non. Rhoncus augue? Tempor porttitor sed, aliquet phasellus a, nisi nunc aliquet nec rhoncus enim porttitor ultrices lacus tristique?</p>#}
{#                                        <a href="https://wrapbootstrap.com/user/themelize_me" class="btn more-link large i-right">Buy Now <i class="default"></i></a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <!--Slide #2 -->#}
{#                        <div class="slide row-fluid second" style="width: 100%; float: left; display: block; background: url('/static/images/bg-slide2.jpg');">#}
{#                            <div class="container">#}
{#                                <div class="row">#}
{#                                    <div class="col-md-6 caption">#}
{#                                        <h2 class="enlarge"><span class="em">Flexor</span> Bootstrap Theme</h2>#}
{#                                        <h4>High quality, responsive theme!</h4>#}
{#                                        <p>Perfect for your App, Web service, company or portfolio! Magna tincidunt sociis ac integer amet non. Rhoncus augue? Tempor porttitor sed, aliquet phasellus a, nisi nunc aliquet nec rhoncus enim porttitor ultrices lacus tristique?</p>#}
{#                                        <a href="https://wrapbootstrap.com/user/themelize_me" class="btn more-link large"><i class="default"></i> Learn More</a>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
            </div>
        </div>
    </section>
</div>

webshop/templates/tags/top_menu.html
<div class="menu_top">
    <nav role="navigation">
        <div class="region region-navigation">
            <ul class="menu nav navbar-nav">

                <li><a href="/">Главная</a></li>
                {% for page in top_menu_pages %}
                    <li><a href="/page/{{ page.slug }}">{{ page.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </nav>
</div>