webshop/cart/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.cart.views',
    url(r'^$', 'cart_view', {'template_name':'cart/cart.html'}, name='show_cart'),
)

webshop/news/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.news.views',
# Главная страница
    url(r'^post/(?P<news_slug>[-\w]+)/$', 'news_view',
           {'template_name':'news/news.html'}, name='news'),
    url(r'^allnews/$', 'news_all_view',
           {'template_name':'news/news_all.html'}, name='news_all'),
    )

webshop/pages/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url
from django.contrib import admin

from webshop import settings

from webshop.pages.views import *

urlpatterns = patterns('webshop.pages.views',
    # url(r'^(?P<slug>[-_\w]+)/$', PageView.as_view(), name='page'),
    # url(r'^', PageList.as_view(), name='blog_posts'),
    url(r'^(?P<slug>[-_\w]+)/$', 'pageView',
        {'template_name':'pages/page.html'},
        name='page'),
)

webshop/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, include, url
from django.contrib import admin

from webshop import settings
from dajaxice.core import  dajaxice_autodiscover, dajaxice_config

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^webshop/', include('webshop.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # General application URLs
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('webshop.accounts.urls')),
    url(r'^', include('webshop.catalog.urls')),
    url(r'^cart/', include('webshop.cart.urls')),
    url(r'^page/', include('webshop.pages.urls')),
    url(r'^blog/', include('webshop.pages.blogurls')),
    url(r'^checkout/', include('webshop.checkout.urls')),
    url(r'^', include('webshop.news.urls')),
    url(r'^search/', include('webshop.search.urls')),
    url(r'^review/$', include('webshop.pages.reviewurls')),


    # enable language choice
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),

    # урл для robokassa
    # url(r'^robokassa/', include('robokassa.urls')),
    # url(r'^robokassa/result/', include('webshop.checkout.robokassa_urls')),
    url(r'^robokassa/', include('robokassa.urls')),

    )


# if settings.DEBUG:
#     urlpatterns += patterns('',
#     url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.STATIC_ROOT}),
#         # if work then show 404 Directory indexes are not allowed here.
#     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.MEDIA_ROOT}),
#         )

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
        )


handler404 = 'webshop.views.file_not_found_404'

webshop/ajaxapp/models.py
from django.db import models

# Create your models here.

webshop/checkout/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
import decimal

from django.contrib.auth.models import User
# from webshop.accounts.models import UserProfile
from django.db import models
from django.db.models import permalink
from django.utils.translation import ugettext_lazy as _

from webshop.catalog.models import *

class Delivery(models.Model):
    delivery_type = models.CharField(
        verbose_name=u'способ доставки',
        max_length=100,
        choices=(
            ('SPSurface', 'Small Packet Surface'),
            ('SPSAL', 'Small Packet SAL'),
            ('SPA' ,'Small Packet Air'),
            ('PS', 'Parcel Surface'),
            ('EMA', 'EMA'),
        ),
        default='',)
    weight = models.IntegerField(verbose_name=u'Вес', default=0)
    delivery_price = models.DecimalField(max_digits=9, decimal_places=0)
    cart_id_delivery = models.CharField(max_length=50, )

    gift = models.ForeignKey(GiftPrice, verbose_name=u'Доставить подарок', null=True, blank=True)

    def __unicode__(self):
        return '%s' % self.delivery_price

    def is_to_big(self):
        return self.weight > 20000

class BaseOrderInfo(models.Model):
    """Абстрактный класс для заказов"""
    class Meta:
        abstract = True

    # Контактная информация
    email = models.EmailField(max_length=50, verbose_name=(u'Ваш email'))
    phone = models.CharField(max_length=20, verbose_name=(u'Ваш телефон'))
    # Информация об адресе для отправки товара
    shipping_name = models.CharField(max_length=240, verbose_name=(u'ФИО получателя'))
    shipping_address_1 = models.TextField(verbose_name=(u'Адрес доставки'))
    shipping_city = models.CharField(max_length=200, verbose_name=(u'Город'))

    shipping_address_2 = models.TextField(verbose_name=(u'Дополнительный адрес(необязательно)'), blank=True)

    shipping_country = models.CharField(max_length=200, verbose_name=(u'Страна'))
    shipping_zip = models.CharField(max_length=10, verbose_name=(u'Почтовый индекс'))

class Order(BaseOrderInfo):
    """Класс для заказа"""

    # Константы статуса
    SUBMITTED = 1
    PAID = 2
    CURIER = 3

    # Словарь возможных статусов заказа
    ORDER_STATUSES = ((SUBMITTED, _(u'Принято')),
                      (PAID, _(u'Оплачено')),
                      (CURIER, _(u'Оплата квитанцией')),)

    # словарь способа оплаты
    PAYMENT_DICTIONARY = ((1, _(u'Оплатить квитанцию')),
                          (2, _(u'Оплатить Viza, MasterCard, ЯндексДеньги')),)

    # Информация о заказе
    date = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=ORDER_STATUSES, default=SUBMITTED)
    payment_method = models.IntegerField(choices=PAYMENT_DICTIONARY, default=2)
    ip_address = models.IPAddressField()
    last_updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, null=True)
    transaction_id = models.CharField(max_length=20)

    # def cupon_is_zero(self):
    #     return Cupon.objects.get(identifier='zero')

    cupon = models.ForeignKey(Cupon, verbose_name=u'Использованый купон', blank=True, null=True)

    delivery = models.ForeignKey(Delivery, null=True)

    def __unicode__(self):
        return _(u'Order #') + str(self.id)

    @property
    def total(self):
        """Общая сумма заказа"""
        total = decimal.Decimal('0.00')
        order_items = OrderItem.objects.filter(order=self)
        for item in order_items:
            total += item.total
        total = total + self.delivery.delivery_price
        return total

    @permalink
    def get_absolute_url(self):
        """Абсолютная ссылка для просмотра заказа"""
        return ('order_details', (), { 'order_id': self.id })

    def get_shipping_name(self):
        return self.shipping_name

    # переопределяем метод сохранения что бы присвоить zero купон , если никакого другого не присваивали
    def save(self, force_insert=False, force_update=False, using=None):
        if not self.cupon:
            self.cupon = Cupon.objects.get(identifier='zero')
        return super(Order, self).save(force_insert, force_update, using)


class OrderItem(models.Model):
    """Конкретный товар в заказе"""
    product = models.ForeignKey(Product)
    feel = models.ForeignKey(FeelName, unique=False, default=None, null=True)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    order = models.ForeignKey(Order)
    # atribute = models.ForeignKey(ProductVolume, unique=False, default=None, null=False)
    # feel = models.ForeignKey(FeelName, null=True)
    atributes = models.ForeignKey(ProductVolume)


    @property
    def total(self):
        """Сумма для товара"""
        return self.quantity * self.price

    @property
    def name(self):
        """Название товара"""
        return self.product.name

    def get_feel(self):
        try:
            f = self.feel.name
            return  f
        except Exception:
            return None


    def __unicode__(self):
        return self.product.name
               # + ' (' + self.product.sku + ')'

    def get_absolute_url(self):
        """Абсолютная ссылка на товар в корзине"""
        return self.product.get_absolute_url()

class OrderOneClick(models.Model):
    product_name = models.CharField(max_length=128, verbose_name=u'Имя продукта')
    phone = models.CharField(max_length=20, verbose_name=u'Телефон')

    class Meta:
        verbose_name = ('Заказы')
        verbose_name_plural = ('Заказы в 1 клик')
        ordering = ['product_name']

    def __unicode__(self):
        return self.product_name

webshop/pages/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from ckeditor.widgets import CKEditorWidget

from webshop.pages.models import *

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user',)


class PageForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Page
        exclude = ()
        # exclude = ('slug',)

webshop/search/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms

from webshop.search.models import SearchTerm


class SearchForm(forms.ModelForm):
    """Форма поиска"""
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        default_text = u'Search...'
        self.fields['query'].widget.attrs['value'] = default_text
        self.fields['query'].widget.attrs['onfocus'] = "if (this.value == '" + default_text + "')this.value = ''"
    include = ('query',)

    class Meta:
        model = SearchTerm
        exclude = ()


webshop/accounts/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

import decimal
from webshop.settings import ADMIN_EMAIL
from django.core.mail import send_mail, EmailMultiAlternatives
from webshop.checkout.models import Order, OrderItem
from webshop.accounts.forms import UserProfileForm, MyRegistrationForm
from webshop.accounts import profile


@csrf_protect
def register_view(request, template_name="registration/register.html"):
    """Регистрация нового пользователя"""
    page_title = _(u'User Registration')
    request.breadcrumbs(page_title, request.path_info)
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = MyRegistrationForm(postdata)
        if form.is_valid():
            form.save()
            un = postdata.get('username', '')
            # name="password1" т.к. два поля с подтверждением
            pw = postdata.get('password1', '')
            new_user = authenticate(username=un, password=pw)
            if new_user and new_user.is_active:

                # отправляем e-mail о регистрации нового пользователя
                subject = u'polythai.ru регистрация %s' % new_user.username
                message = u' Зарегистрирован новый пользователь %s' % (new_user.username)
                send_mail(subject, message, 'teamer777@gmail.com', [ADMIN_EMAIL], fail_silently=False)

                login(request, new_user)
                # Редирект на url с именем my_account
                url = urlresolvers.reverse('my_account')
                return HttpResponseRedirect(url)
    else:
        form = MyRegistrationForm()

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def my_account_view(request, template_name="registration/my_account.html"):
    """Страница аккаунта пользователя"""
    page_title = _(u'My Account')
    request.breadcrumbs(page_title, request.path_info)
    if request.user.is_superuser:
        orders = Order.objects.all()
    else:
        orders = Order.objects.filter(user=request.user)
    name = request.user.username
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_details_view(request, order_id, template_name="registration/order_details.html"):
    """Информация о сделанном заказе"""
    if request.user.is_superuser:
        order = get_object_or_404(Order, id=order_id)
    else:
        order = get_object_or_404(Order, id=order_id, user=request.user)
    page_title = _(u'Order details for order #') + order_id
    request.breadcrumbs(page_title, request.path_info)
    order_items = OrderItem.objects.filter(order=order)
    total_sum_parse = "%s" % order.total
    total_sum_parse = total_sum_parse.split(".")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def receipt_print_view(request, price, template_name="checkout/receipt_print.html"):
    price = price.split("-")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_info_view(request, template_name="registration/order_info.html"):
    """Представление данных профиля"""
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = UserProfileForm(postdata)
        if form.is_valid():
            profile.set(request)
            url = urlresolvers.reverse('my_account')
            return HttpResponseRedirect(url)
    else:
        user_profile = profile.retrieve(request)
        form = UserProfileForm(instance=user_profile)
    page_title = _(u'Edit Order Information')
    request.breadcrumbs(page_title, request.path_info)
    return render_to_response(template_name, locals(),
                                  context_instance=RequestContext(request))

webshop/ajaxapp/views.py
# Create your views here.

webshop/cart/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

from webshop.cart import cart
from webshop.checkout import checkout
from webshop.checkout.forms import ContactForm, DeliveryForm


@csrf_protect
def cart_view(request, template_name="cart/cart.html"):
    """Представление для отображения корзины"""
    page_title = _(u'Shopping cart')
    if request.method == 'POST':
        postdata = request.POST.copy()

        if postdata.has_key('remove'):
            cart.remove_from_cart(request)

        if postdata.has_key('update'):
            cart.update_cart(request)

        """отправляем request на пересчет корзины по купону"""
        if postdata.has_key('update_cupon'):
            cart.update_cupon_cart(request)


        if postdata.has_key('checkout'):
            checkout_url = checkout.get_checkout_url(request)
            return HttpResponseRedirect(checkout_url)

    deliveryForm = DeliveryForm()

    request.breadcrumbs(u'Корзина', request.path_info)

    # Получаем список всех товаров в корзине из cookies
    #cart_item_count = cart.cart_item_count(request)
    cart_items = cart.get_cart_items(request)
    cart_subtotal = cart.cart_subtotal(request)
    cart_gift = cart.cart_gift_add(request)

    # доставка
    try: 
        delivery = cart.get_delivery(request)
        delivery.save()
        cart_total = cart.cart_total(request)
    except Exception:
        return redirect("/")

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

webshop/news/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _

from models import News

from django.shortcuts import get_object_or_404


def news_view(request, news_slug, template_name="news.html"):
    """Представление для конкретной новости"""
    news = get_object_or_404(News, slug=news_slug)
    return render_to_response(template_name,
            {'news': news,}, context_instance=RequestContext(request))

def news_all_view(request, template_name="news_all.html"):
    """Представление для конкретной новости"""
    news = News.objects.all()
    return render_to_response(template_name,
            {'news': news}, context_instance=RequestContext(request))


webshop/templates/cart/cart.html
{% extends "catalog.html" %}
{% load i18n %}
{% load catalog_filters %}
{% load thumbnail %}{% block content %}
{% block slider %}
{% endblock %}
{% block tri_bloka %}
{% endblock %}

{% block onload_cart_script %}
    <script>
        window.onload = function(){
            Dajaxice.webshop.ajaxapp.onload_cart(Dajax.process,{});
        }
    </script>
{% endblock %}

        <div id="cart">
{#            <div class="row">#}

                <div class="col-xs-12">
                    <div class="row">
                        <div class="col-xs-3">
                            <h1>Ваша корзина</h1>
                        </div>
                    </div>
                </div>

                {#вывод промокода#}
                <div class="col-xs-12 kupon">
                    <p style=" color: red; ">Введите Ваш купон - промокод:</p>
                    <form method="post" action=".">{% csrf_token %}
                        <input type="text" name="cupon" value="" id="cupon" size="10" style=" width: 147px; margin-right: 10px;"/>
                        <button class="btn btn-success" type="submit" name="update_cupon">
                            <i class="icon-refresh icon-white" style="margin-right: 5px;"></i><span>Пересчитать</span>
                        </button>
                    </form>
                </div>
                <div class="col-xs-12">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">{% trans "Product" %}</th>
                                    <th scope="col">Характеристики</th>
                                    <th scope="col">{% trans "Price" %}</th>
                                    <th>Кол-во</th>
                                    <th></th>
                                    <th></th>
                                    <th scope="col" class="right">{% trans "Total" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% if cart_items %}
                                    {% for item in cart_items %}
                                <tr>
                                    <td>
    {#                                    {% thumbnail item.get_default_image "50x50" crop="center" as im %}#}
                                            <img class="item_img" src="/media/{{ item.get_default_image }}" width="50" height="50">
    {#                                    {% endthumbnail %}#}
                                        <a href="{{ item.get_absolute_url }}" class="cart">
                                        {{ item.name }}
                                        </a>
                                    </td>
                                    <td>
                                    <div class="panel-group" id="accordion">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a class="accordion_button" data-toggle="collapse" data-parent="#accordion" href="#item{{ item.id }}">Подробнее <i class="fa fa-caret-down"></i></a>
                                                </h4>
                                            </div>
                                            <div id="item{{ item.id }}" class="panel-collapse collapse" style="height: auto;">
                                                <div class="panel-body" style="text-align: left">
                                                    <span><i class="fa fa-shopping-cart"></i> {{ item.atributes.volume }}</span> <br/>
                                                    <span><i class="fa fa-tachometer"></i> {{ item.atributes.weight }} гр.</span> <br/>
                                                    <span><i class="fa fa-cutlery"></i> {{ item.feel.name }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    </td>
                                    <td>
                                        {{ item.price }} <i class="fa fa-rub"></i>
                                    </td>
                                    <td class="right">
                                        <form method="post" action="." class="cart">{% csrf_token %}
                                            {#<label class="control-label" for="quantity">{% trans "Quantity" %}:</label>#}
                                            <input type="text" name="quantity" value="{{ item.quantity }}" id="quantity" size="2" class="quantity" maxlength="5" />
                                            <input type="hidden" name="item_id" value="{{ item.id }}" />
                                    </td>
                                    <td>
                                            <input type="hidden" name="item_id" value="{{ item.id }}" />
                                            <button class="btn btn-success" type="submit" name="update">
                                            <i class="icon-refresh icon-white"></i> <span>Обновить</span></button>
                                        </form>
                                    </td>
                                    <td>
                                        <form method="post" action="." class="cart">{% csrf_token %}
                                            <input type="hidden" name="item_id" value="{{ item.id }}" />
                                            <button class="btn btn-danger" type="submit" name="remove">
                                            <i class="icon-trash icon-white"></i> {% trans "Remove" %}</button>
                                        </form>
                                    </td>
                                    <td class="right">{{ item.total }} <i class="fa fa-rub"></i></td>
                                </tr>
                                {% endfor %}
                                {% else %}
                                <tr>
                                    <td colspan="6" style="height:30px;">
                                        {% trans "Your cart is empty" %}
                                    </td>
                                </tr>
                                {% endif %}
                            </tbody>

                            <tfoot>
                                <tr>
                                    <th colspan="5">Стоимость товаров:</th>
                                    <th>{{ cart_subtotal }} {% trans "руб." %}</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
{#            таблица доставки#}
            {% if cart_items %}
                <div class="col-xs-7 delivery_all">
                    <div class="row">
                        <div class="col-xs-7">
                            <form action="." method="POST" id="rb_delivery">
                                {% csrf_token %}
                                {{ deliveryForm.delivery.errors }}
                                <label for="id_delivery"><i class="fa fa-plane"></i> <strong>Выберите способ доставки: </strong></label>
                                {{ deliveryForm.delivery }}
                            </form>
                        </div>
                        <div class="col-xs-5 current_delivery">
                            <h4><strong>Текущий способ доставки:</strong></h4>
                            <p>Способ доставки: <span id="type_ajax">{{ delivery.delivery_type }}</span></p>
                            <p style="{% if delivery.is_to_big %}color: red;{% endif %}">Вес посылки {% if delivery.is_to_big %}слишком большой{% endif %}: <span id="weight_ajax">{{ delivery.weight }} гр.</span></p>
                            <p>{% if not delivery.is_to_big %}Стоимость доставки: <span id="price_ajax">{{ delivery.delivery_price }} руб.</span> {% endif %}</p>
                        </div>
                    </div>
                </div>
                <div class="col-xs-5">
                    {#вывод подарков#}
                    {% if cart_gift %}
                        <div class="gift_in_cart">
                            <h4><strong>Для Вас есть подарок!</strong></h4>
                                <div style="">
{#                                    {% thumbnail cart_gift.url "100x100" crop="center" as im %}#}
{#                                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" align="left">#}
{#                                    {% endthumbnail %}#}
                                    <img src="/media/{{ cart_gift.url }}" width="100" height="100" alt=""/>
                                    <p>{{ cart_gift.name }}</p>
                                    <p>{{ cart_gift.description|truncatewords:100|safe }}</p>
                                </div>
                        </div>
                    {% endif %}
                    <p style="font-weight: bold;" id="price">{% if not delivery.is_to_big %}<span>ИТОГО: </span>{{ cart_total }} <span>руб.</span>{% endif %}</p>
                </div>
                <div class="col-xs-12">
                    <form style="float: right;" name="testrb" method="post" action="." class="cart">{% csrf_token %}
                        {# <button {% if delivery.is_to_big %}disabled="disabled"{% endif %} class="btn btn-success" type="submit" name="checkout"> #}
                        <button class="btn btn-success" type="submit" name="checkout">
                        <i class="icon-shopping-cart icon-white" style="margin-right: 5px;"></i><span>Оформить заказ</span></button>
                    </form>
                </div>
            {% endif %}
{#        </div>#}
    </div>



{% endblock %}