webshop/cart/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.cart.views',
    url(r'^$', 'cart_view', {'template_name':'cart/cart.html'}, name='show_cart'),
)

webshop/news/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url


urlpatterns = patterns('webshop.news.views',
# Главная страница
    url(r'^post/(?P<news_slug>[-\w]+)/$', 'news_view',
           {'template_name':'news/news.html'}, name='news'),
    url(r'^allnews/$', 'news_all_view',
           {'template_name':'news/news_all.html'}, name='news_all'),
    )

webshop/pages/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, url
from django.contrib import admin

from webshop import settings

from webshop.pages.views import *

urlpatterns = patterns('webshop.pages.views',
    # url(r'^(?P<slug>[-_\w]+)/$', PageView.as_view(), name='page'),
    # url(r'^', PageList.as_view(), name='blog_posts'),
    url(r'^(?P<slug>[-_\w]+)/$', 'pageView',
        {'template_name':'pages/page.html'},
        name='page'),
)

webshop/urls.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.conf.urls import patterns, include, url
from django.contrib import admin

from webshop import settings
from dajaxice.core import  dajaxice_autodiscover, dajaxice_config

dajaxice_autodiscover()
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^webshop/', include('webshop.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin_tools/', include('admin_tools.urls')),
    url(dajaxice_config.dajaxice_url, include('dajaxice.urls')),
    # url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # General application URLs
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('webshop.accounts.urls')),
    url(r'^', include('webshop.catalog.urls')),
    url(r'^cart/', include('webshop.cart.urls')),
    url(r'^page/', include('webshop.pages.urls')),
    url(r'^blog/', include('webshop.pages.blogurls')),
    url(r'^checkout/', include('webshop.checkout.urls')),
    url(r'^', include('webshop.news.urls')),
    url(r'^search/', include('webshop.search.urls')),
    url(r'^review/$', include('webshop.pages.reviewurls')),


    # enable language choice
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),

    # урл для robokassa
    # url(r'^robokassa/', include('robokassa.urls')),
    # url(r'^robokassa/result/', include('webshop.checkout.robokassa_urls')),
    url(r'^robokassa/', include('robokassa.urls')),

    )


# if settings.DEBUG:
#     urlpatterns += patterns('',
#     url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.STATIC_ROOT}),
#         # if work then show 404 Directory indexes are not allowed here.
#     url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#         {'document_root': settings.MEDIA_ROOT}),
#         )

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
        )


handler404 = 'webshop.views.file_not_found_404'

webshop/accounts/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from webshop.checkout.models import BaseOrderInfo


class UserProfile(BaseOrderInfo):
    """Профиль пользователя"""
    user = models.ForeignKey(User, unique=True)

    def __unicode__(self):
        return _(u'Профиль: ') + self.user.username

    class Meta:
        verbose_name_plural = _(u'Профили пользователей')

webshop/ajaxapp/models.py
from django.db import models

# Create your models here.

webshop/cart/models.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
import decimal

from django.db import models

from webshop.catalog.models import *


class CartItem(models.Model):

    cart_id = models.CharField(max_length=50)
    date_added = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    product = models.ForeignKey(Product, unique=False)

    atributes = models.ForeignKey(ProductVolume, unique=False)

    feel = models.ForeignKey(FeelName, unique=False, default=None, null=True)

    cupon = models.ForeignKey(Cupon, blank=True, null=True, default=2)

    class Meta:
        db_table = 'cart_items'
        ordering = ['date_added']

    @property
    def total(self):
        """Метод для подсчета суммы, цена товара * кол-во"""
        total = decimal.Decimal("0.00")
        total = self.quantity * self.price
        # total = "%d" % total
        return total

    @property
    def name(self):
        """Получение названия товара в корзине"""
        return self.product.name

    @property
    def price(self):
        """Получение цены товара в корзине"""
        set_price = decimal.Decimal("0.00")
        if self.atributes.new_price != 0.00:
            set_price = self.atributes.new_price
        else:
            set_price = self.atributes.price
        return set_price

    def get_default_image(self):
        # получаем дефолтыне изображения товаров
        image = ProductImage.objects.get(product=self.product, default=True).url
        return image

    def get_absolute_url(self):
        """Получение абсолютной ссылки на товар"""
        return self.product.get_absolute_url()

    def augment_quantity(self, quantity):
        """Изменение количества товара в корзине"""
        if quantity.isdigit():
            self.quantity = self.quantity + int(quantity)
            self.save()

webshop/accounts/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _

from captcha.fields import CaptchaField

from models import UserProfile


class UserProfileForm(forms.ModelForm):
    """Форма для профиля пользователя"""
    class Meta:
        model = UserProfile
        exclude = ('user',)


class MyRegistrationForm(forms.ModelForm):

    error_messages = {
        'duplicate_username': _("A user with that username already exists."),
        'password_mismatch': _("The two password fields didn't match."),
    }
    username = forms.RegexField(label=_("Username"), max_length=100,
        regex=r'^[\w.@+-]+$',
        help_text = u"Пожалуйста введите имя пользователя латинскими буквами и цифрами не более 40 символов, допускаются также следующие символы: @ . + - _ ",
        error_messages = {
            'invalid': _("This value may contain only letters, numbers and "
                         "@/./+/-/_ characters.")})
    password1 = forms.CharField(label=_("Password"),
                                help_text = u"Пароль может состоять из Заглавных и прописных латинских букв и цифр",
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"),
        widget=forms.PasswordInput,
        help_text = _("Enter the same password as above, for verification."))
    captcha = CaptchaField(label=u'Введите символы с картинки',
                           help_text = u"Введите то что вы видите на картинке в рядом стоящее поле",)

    class Meta:
        model = User
        fields = ("username",)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])

    def clean_password(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'])
        return password2

    def save(self, commit=True):
        user = super(MyRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



webshop/pages/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _
from ckeditor.widgets import CKEditorWidget

from webshop.pages.models import *

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user',)


class PageForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Page
        exclude = ()
        # exclude = ('slug',)

webshop/search/forms.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django import forms

from webshop.search.models import SearchTerm


class SearchForm(forms.ModelForm):
    """Форма поиска"""
    def __init__(self, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        default_text = u'Search...'
        self.fields['query'].widget.attrs['value'] = default_text
        self.fields['query'].widget.attrs['onfocus'] = "if (this.value == '" + default_text + "')this.value = ''"
    include = ('query',)

    class Meta:
        model = SearchTerm
        exclude = ()


webshop/accounts/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404
from django.core import urlresolvers
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

import decimal
from webshop.settings import ADMIN_EMAIL
from django.core.mail import send_mail, EmailMultiAlternatives
from webshop.checkout.models import Order, OrderItem
from webshop.accounts.forms import UserProfileForm, MyRegistrationForm
from webshop.accounts import profile


@csrf_protect
def register_view(request, template_name="registration/register.html"):
    """Регистрация нового пользователя"""
    page_title = _(u'User Registration')
    request.breadcrumbs(page_title, request.path_info)
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = MyRegistrationForm(postdata)
        if form.is_valid():
            form.save()
            un = postdata.get('username', '')
            # name="password1" т.к. два поля с подтверждением
            pw = postdata.get('password1', '')
            new_user = authenticate(username=un, password=pw)
            if new_user and new_user.is_active:

                # отправляем e-mail о регистрации нового пользователя
                subject = u'polythai.ru регистрация %s' % new_user.username
                message = u' Зарегистрирован новый пользователь %s' % (new_user.username)
                send_mail(subject, message, 'teamer777@gmail.com', [ADMIN_EMAIL], fail_silently=False)

                login(request, new_user)
                # Редирект на url с именем my_account
                url = urlresolvers.reverse('my_account')
                return HttpResponseRedirect(url)
    else:
        form = MyRegistrationForm()

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def my_account_view(request, template_name="registration/my_account.html"):
    """Страница аккаунта пользователя"""
    page_title = _(u'My Account')
    request.breadcrumbs(page_title, request.path_info)
    if request.user.is_superuser:
        orders = Order.objects.all()
    else:
        orders = Order.objects.filter(user=request.user)
    name = request.user.username
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_details_view(request, order_id, template_name="registration/order_details.html"):
    """Информация о сделанном заказе"""
    if request.user.is_superuser:
        order = get_object_or_404(Order, id=order_id)
    else:
        order = get_object_or_404(Order, id=order_id, user=request.user)
    page_title = _(u'Order details for order #') + order_id
    request.breadcrumbs(page_title, request.path_info)
    order_items = OrderItem.objects.filter(order=order)
    total_sum_parse = "%s" % order.total
    total_sum_parse = total_sum_parse.split(".")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def receipt_print_view(request, price, template_name="checkout/receipt_print.html"):
    price = price.split("-")
    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

@login_required
def order_info_view(request, template_name="registration/order_info.html"):
    """Представление данных профиля"""
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = UserProfileForm(postdata)
        if form.is_valid():
            profile.set(request)
            url = urlresolvers.reverse('my_account')
            return HttpResponseRedirect(url)
    else:
        user_profile = profile.retrieve(request)
        form = UserProfileForm(instance=user_profile)
    page_title = _(u'Edit Order Information')
    request.breadcrumbs(page_title, request.path_info)
    return render_to_response(template_name, locals(),
                                  context_instance=RequestContext(request))

webshop/ajaxapp/views.py
# Create your views here.

webshop/cart/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.csrf import csrf_protect

from webshop.cart import cart
from webshop.checkout import checkout
from webshop.checkout.forms import ContactForm, DeliveryForm


@csrf_protect
def cart_view(request, template_name="cart/cart.html"):
    """Представление для отображения корзины"""
    page_title = _(u'Shopping cart')
    if request.method == 'POST':
        postdata = request.POST.copy()

        if postdata.has_key('remove'):
            cart.remove_from_cart(request)

        if postdata.has_key('update'):
            cart.update_cart(request)

        """отправляем request на пересчет корзины по купону"""
        if postdata.has_key('update_cupon'):
            cart.update_cupon_cart(request)


        if postdata.has_key('checkout'):
            checkout_url = checkout.get_checkout_url(request)
            return HttpResponseRedirect(checkout_url)

    deliveryForm = DeliveryForm()

    request.breadcrumbs(u'Корзина', request.path_info)

    # Получаем список всех товаров в корзине из cookies
    #cart_item_count = cart.cart_item_count(request)
    cart_items = cart.get_cart_items(request)
    cart_subtotal = cart.cart_subtotal(request)
    cart_gift = cart.cart_gift_add(request)

    # доставка
    try: 
        delivery = cart.get_delivery(request)
        delivery.save()
        cart_total = cart.cart_total(request)
    except Exception:
        return redirect("/")

    return render_to_response(template_name, locals(),
                              context_instance=RequestContext(request))

webshop/news/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _

from models import News

from django.shortcuts import get_object_or_404


def news_view(request, news_slug, template_name="news.html"):
    """Представление для конкретной новости"""
    news = get_object_or_404(News, slug=news_slug)
    return render_to_response(template_name,
            {'news': news,}, context_instance=RequestContext(request))

def news_all_view(request, template_name="news_all.html"):
    """Представление для конкретной новости"""
    news = News.objects.all()
    return render_to_response(template_name,
            {'news': news}, context_instance=RequestContext(request))


webshop/templates/catalog/lider.html
{% extends "catalog.html" %}
{% load thumbnail %}
{% load i18n %}

{% block slider %}
{% endblock %}

{% block tri_bloka %}
{% endblock %}


{% block content %}
    <div id="catalog">
            <div class="row">
                   <div class="col-xs-12">
                        <h1>Лидеры продаж</h1>
                   </div>

{#                    если продукты существуют#}
                    {% if liders %}
{#                        цыкл по продуктам (осуществляется проход до тех пор пока есть продукты)#}
                        {% for p in liders %}
                            <div class="col-xs-4">
                                <div class="product_thumbnail">
                                    <a href="{{ p.get_absolute_url }}">
{#                                        {% thumbnail p.image_url "200x200" crop="center" as im %}#}
                                            <img src="/media/{{ p.image_url }}" width="200">
{#                                        {% endthumbnail %}#}
                                        <br />
                                        <h2>{{ p.name }}</h2>
                                    </a>
                                    {% if p.is_not_available %} <span style="color: red">нет в наличии</span>{% endif %}
                                    {% if p.sale_price.new_price != 0.00 %}
                                        <div class="price_was">
                                            {% trans "Was" %}: <span>{{ p.sale_price.price }} {% trans "руб." %}</span>
                                        </div>
                                        <div class="price_now">
                                            {% trans "Now" %}:<span> {{ p.sale_price.new_price }} {% trans "руб." %} *</span>
                                        </div>
                                        <p>*за объем: {{ p.sale_price.volume }} мл.</p>
                                    {% else %}
                                        <p>{{ p.sale_price.price }} {% trans "руб." %}</p>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
{#                        закончить цыкл#}

{#                    иначе .... если продукты не существуют#}
                    {% else %}
                       <div class="none_tovar">
                        {% trans "В категории отсутствуют товары" %}
                       </div>
                    {% endif %}
{#                    закончить условие "если"#}
            </div>
    </div>
{% endblock %}

webshop/templates/catalog/product.html
{% extends "catalog.html" %}
{% load i18n %}
{% load catalog_filters %}
{% load thumbnail %}
{% load cropping %}

{% block product_js %}
    <script src="/static/js/slides.min.jquery.js"></script>
    <script>
		$(function(){
			$('#products').slides({
				preload: true,
				preloadImage: 'img/loading.gif',
				effect: 'slide, fade',
				crossfade: true,
				slideSpeed: 200,
				fadeSpeed: 500,
				generateNextPrev: true,
				generatePagination: false
			});
		});
	</script>
    <link rel="stylesheet" href="/static/css/product.css">

{% endblock %}

{% block slider %}
{% endblock %}
{% block tri_bloka %}
{% endblock %}

{% block content %}
    <div id="product_lict">
            <div class="row row-fluid">

                <div class="col-xs-12 product_text">
                    <h1>
                        {{ p.name }}{% if p.is_not_available %} <span style="color: red">- нет в наличии</span>{% endif %}
                    </h1>
                </div>


                <div class="col-xs-5">
{#                    {% thumbnail product_image.url "298x319" crop="center" as im %}#}
{#                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">#}
{#                    {% endthumbnail %}#}
                    {% if images %}

                        <div id="products_example">
                            <div id="products">
                                <div class="slides_container">
                                    {% for image in images %}
                                        <a name="">
{#                                        {% thumbnail image.url "300x300" crop="center" as im %}#}
{#                                            <img src="{{ im.url }}" >#}
{#                                        {% endthumbnail %}#}
{#                                            <img src="{% cropped_thumbnail image "cropping" scale=1%}">#}
                                            <img src="/media/{{ image.url }}" width="300" height="300">
                                        </a>
                                    {% endfor %}
                                </div>
                                <ul class="pagination">
                                    {% for image in images %}
                                        <li><a href="#"><img src="/media/{{ image.url }}" width="55" alt=""/></a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>

                    {% else %}
                        <p>Нет фото</p>
                    {% endif %}

                </div>

                <div class="tabbable">
                    <div class="col-xs-7">

                        <h2>Описание:</h2>
                        <div class="tab-pane" id="description">{{ p.description|truncatewords:30|safe }}</div>
                        <br/>
                        <div class="row">
                            <div class="col-xs-12" style="height: 40px;">
                                <div class="row">
                                    <div class="col-xs-6">Брэнд:</div>
                                    <div class="col-xs-6">{{ p.brand_name.name }}</div>
                                </div>
                            </div>
                            <div class="col-xs-12" style="height: 40px;">
                                <div class="row">
                                    <div class="col-xs-6">Объем:</div>
                                    <div class="col-xs-6">
                                        <select onchange="Dajaxice.webshop.ajaxapp.change_atrs(Dajax.process, {'option':this.value})" size="1">
                                            {% for atr in atrs %}
                                                <option value="{{ atr.id }}">{{ atr.volume }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12" style="height: 40px;">
                                <div class="row">
                                    <div class="col-xs-6">Вес:</div>
                                    <div class="col-xs-6"><span id="weight">{{ atrs_default.weight }} гр.</span></div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-xs-7">
                    <div class="row">
                        <div class="price_cart">
                            <div class="col-xs-6">
                                {% if p.feel.count > 0 %}
                                    <p>Выберите разновидность:</p> <br/>
                                {% endif %}

                                <div id="super_price" class="{% if p.get_atributes.new_price == 0.00 %}hidden{% endif %}">
                                    <div class="price_was">
                                        {% trans "Was" %}: <span id="price">{{ atrs_default.price }} {% trans "руб." %}</span>
                                    </div>
                                    <br/>
                                    <div class="price_now">
                                        <span id="new_price">{% trans "Now" %}: {{ atrs_default.new_price }} руб.</span>
                                    </div>
                                </div>
                                <div id="old_price" class="{% if p.get_atributes.new_price != 0.00 %}hidden{% endif %}">
                                    <span id="price_old">{% trans "Price" %}: {{ atrs_default.price }} {% trans "руб." %} </span>
                                </div>

{#                                {% if p.sale_price.new_price != 0.00 %}#}
{#                                    <div class="price_was">#}
{#                                        {% trans "Was" %}: <span>{{ p.sale_price.price }} {% trans "руб." %}</span>#}
{#                                    </div>#}
{#                                    <div class="price_now">#}
{#                                        {% trans "Now" %}:<span> {{ p.sale_price.new_price }} {% trans "руб." %} *</span>#}
{#                                    </div>#}
{#                                    <p>*за объем: {{ p.sale_price.volume }} мл.</p>#}
{#                                {% else %}#}
{#                                    <p>{{ p.sale_price.price }} {% trans "руб." %}</p>#}
{#                                {% endif %}#}


                            </div>

                            <div class="col-xs-6">
                                <form method="post" action="." class="cart">{% csrf_token %}
                                    <div class="hidden">
                                        {{ form.product_slug }}
                                    </div>
                                    <div class="hidden">
                                        <input id="atr_value" name="atr_value" type="hidden" value="{{ atrs.0.id }}"/>
                                    </div>
                                    {% if p.feel.count > 0 %}
                                        <div class="feel">
                                            {% if error.feel %}{{ error.feel }}<div class="error">{% endif %}
{#                                            <label for="id_feel">Выберите вкус:</label>#}
                                            <select name="feel" id="id_feel">
                                                {% for feel in p.feel.all %}
                                                    <option value="{{ feel.id }}">{{ feel.name }}</option>
                                                {% endfor %}
                                            </select>
                                            {% if error.feel %}</div>{% endif %}
                                        </div>
                                    {% endif %}
                                    <div class="quantity">
                                        <br/><label for="id_quantity">Количество:</label>
                                        {{ form.quantity }}
                                    </div>
{#                                    <input class="btn btn-success" type="submit" value="{% trans "Add To Cart" %}"#}
{#                                    name="submit" alt=" {% trans "Add To Cart" %}" />#}

                                    <button class="btn btn-success {% if p.is_not_available %}disabled{% endif %}" type="submit" name="submit">
                                        <i class="icon-shopping-cart icon-white" style="margin-right: 5px;"></i><span>Добавить в корзину</span>
                                    </button>

                                </form>
{#                                <form method="post" action="." class="cart">{% csrf_token %}#}
{#                                    {{ form.as_p }}#}
{#                                </form>#}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12">
                    <h4>Описание:</h4>
                    <div class="tab-pane" id="description">{{ p.description|safe }}</div>
                </div>

            </div>



    </div>


<div id="message_show" class="hidden">
    <div class="message_inner">
        <h6>Спасибо!</h6>
        <p>В ближайшее время наш менеджер свяжется с Вами</p>
        <button  class="btn btn-primary" onclick="closeMessage();">Закрыть</button>
    </div>
</div>
{% endblock %}

{#подключаем скрипт blueimp только на этой странице что бы не засорять код#}
{% block bottom_script %}
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls " style="display: none;">
        <div class="slides" style="width: 7684px;"></div>
        <h3 class="title">Галерея</h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
    <script type="text/javascript" src="/static/blueimp/js/blueimp-gallery.min.js"></script>
    <script type="text/javascript">
{#		document.getElementById('links').onclick = function (event) {#}
{#			event = event || window.event;#}
{#			var target = event.target || event.srcElement,#}
{#				link = target.src ? target.parentNode : target,#}
{#				options = {index: link, event: event},#}
{#				links = this.getElementsByTagName('a');#}
{#			blueimp.Gallery(links, options);#}
{#		};#}
{#		document.getElementById('links2').onclick = function (event) {#}
{#			event = event || window.event;#}
{#			var target = event.target || event.srcElement,#}
{#				link = target.src ? target.parentNode : target,#}
{#				options = {index: link, event: event},#}
{#				links = this.getElementsByTagName('a');#}
{#			blueimp.Gallery(links, options);#}
{#		};#}
	</script>
{% endblock %}